package com.example.demo.model;

public class DirMgtPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dir_mgt.id
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dir_mgt.name
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dir_mgt.type
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dir_mgt.owner
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dir_mgt.uuid
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    private String uuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dir_mgt.id
     *
     * @return the value of dir_mgt.id
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dir_mgt.id
     *
     * @param id the value for dir_mgt.id
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dir_mgt.name
     *
     * @return the value of dir_mgt.name
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dir_mgt.name
     *
     * @param name the value for dir_mgt.name
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dir_mgt.type
     *
     * @return the value of dir_mgt.type
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dir_mgt.type
     *
     * @param type the value for dir_mgt.type
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dir_mgt.owner
     *
     * @return the value of dir_mgt.owner
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dir_mgt.owner
     *
     * @param owner the value for dir_mgt.owner
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dir_mgt.uuid
     *
     * @return the value of dir_mgt.uuid
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dir_mgt.uuid
     *
     * @param uuid the value for dir_mgt.uuid
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
}