package com.example.demo.repository;

import com.example.demo.model.DirMgtPO;
import com.example.demo.model.DirMgtPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface DirMgtPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dir_mgt
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    long countByExample(DirMgtPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dir_mgt
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    int deleteByExample(DirMgtPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dir_mgt
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dir_mgt
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    int insert(DirMgtPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dir_mgt
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    int insertSelective(DirMgtPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dir_mgt
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    List<DirMgtPO> selectByExample(DirMgtPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dir_mgt
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    DirMgtPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dir_mgt
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") DirMgtPO record, @Param("example") DirMgtPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dir_mgt
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    int updateByExample(@Param("record") DirMgtPO record, @Param("example") DirMgtPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dir_mgt
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    int updateByPrimaryKeySelective(DirMgtPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dir_mgt
     *
     * @mbg.generated Fri Feb 07 17:43:19 CST 2020
     */
    int updateByPrimaryKey(DirMgtPO record);
}